// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6OGm1yNU6EWsQH0Np1Uwu9_yVcZwwmmw',
    appId: '1:148460265367:web:afc1c9d244709077236ed2',
    messagingSenderId: '148460265367',
    projectId: 'works-cffaa',
    authDomain: 'works-cffaa.firebaseapp.com',
    storageBucket: 'works-cffaa.appspot.com',
    measurementId: 'G-WPZX46J7XP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ_3yhY2TMuIsHVAPggcHXyi1qwjwVCvQ',
    appId: '1:148460265367:android:cfffea4f4abbf494236ed2',
    messagingSenderId: '148460265367',
    projectId: 'works-cffaa',
    storageBucket: 'works-cffaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqAbySCMGbLpMyoJM_QBYQTWTeG3DKVj8',
    appId: '1:148460265367:ios:b6d7aa4c47eb720d236ed2',
    messagingSenderId: '148460265367',
    projectId: 'works-cffaa',
    storageBucket: 'works-cffaa.appspot.com',
    iosBundleId: 'com.example.workwell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqAbySCMGbLpMyoJM_QBYQTWTeG3DKVj8',
    appId: '1:148460265367:ios:05bedeb4f24fef23236ed2',
    messagingSenderId: '148460265367',
    projectId: 'works-cffaa',
    storageBucket: 'works-cffaa.appspot.com',
    iosBundleId: 'com.example.workwell.RunnerTests',
  );
}
